apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.fullname" . }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
