graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Container View: mnemos"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 3 ["mnemos"]
      style 3 fill:#ffffff,stroke:#0b4884,color:#0b4884

      4["<div style='font-weight: bold'>Model Serving</div><div style='font-size: 70%; margin-top: 0px'>[Container: OpenAI-compatible HTTP, llama.cpp]</div><div style='font-size: 80%; margin-top:10px'>Local LLM inference for<br />extraction and synthesis</div>"]
      style 4 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

  end