apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "neo4j.selectorLabels" . | nindent 4 }}
  ports:
    - name: bolt
      port: {{ .Values.service.boltPort }}
      targetPort: bolt
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
